---
apiVersion: v1
kind: Service
metadata:
  name: papermc
spec:
  ports:
    - name: server
      port: 25565
      targetPort: minecraft
      protocol: TCP
    - name: rcon
      port: 25575
      targetPort: rcon
  type: LoadBalancer
  selector:
    app: papermc
